// Auto-generated by Dataform IntelliJ Plugin — do not edit

interface I_SqlxColumnDescriptor {
}

interface I_ActionConfig_Target {
  /** The Google Cloud project (database) of the action. */
  project?: string;
  /** The dataset (schema) of the action. For notebooks, this is the location. */
  dataset?: string;
  /** The name of the action. */
  name?: string;
  /** flag for when we want to add assertions of this dependency in dependency_targets as well. */
  includeDependentAssertions?: boolean;
}

interface I_ActionConfig_ColumnDescriptor {
  /** The identifier for the column, using multiple parts for nested records. */
  path?: string[];
  /** A text description of the column. */
  description?: string;
  /** A list of BigQuery policy tags that will be applied to the column. */
  bigqueryPolicyTags?: string[];
  /** A list of tags for this column which will be applied. */
  tags?: string[];
}

interface I_ActionConfig_TableAssertionsConfig {
  /** Column(s) which constitute the dataset's unique key index. If set, the resulting assertion will fail if there is more than one row in the dataset with the same values for all of these column(s). */
  uniqueKey?: string[];
  uniqueKeys?: I_ActionConfig_TableAssertionsConfig_UniqueKey[];
  /** Column(s) which may never be `NULL`. If set, the resulting assertion will fail if any row contains `NULL` values for these column(s). */
  nonNull?: string[];
  /** General condition(s) which should hold true for all rows in the dataset. If set, the resulting assertion will fail if any row violates any of these condition(s). */
  rowConditions?: string[];
}

interface I_ActionConfig_TableAssertionsConfig_UniqueKey {
  uniqueKey?: string[];
}

interface I_ActionConfig_IcebergTableConfig {
  /** The file format for the BigQuery table. */
  fileFormat?: "FILE_FORMAT_UNSPECIFIED" | "PARQUET";
  /** The connection specifying the credentials to be used to read and write to external storage, such as Cloud Storage. The connection can have the form `{project}.{location}.{connection_id}` or `projects/{project}/locations/{location}/connections/{connection_id}", or be set to DEFAULT. */
  connection?: string;
  /** The name of the Cloud Storage bucket where table data is stored. This value is be used to construct the storage URI in the following way: `gs://{bucket_name}/{table_folder_root}/{table_folder_subpath}``. If `storage_uri` is provided, this value is ignored. */
  bucketName?: string;
  /** The name of the first-level folder inside the Cloud Storage bucket where table data is stored. This value will be used to construct the storage URI in the following way: `gs://{bucket_name}/{table_folder_root}/{table_folder_subpath}``. If `storage_uri` is provided, this value is ignored. */
  tableFolderRoot?: string;
  /** The path under the first-level folder of the Cloud Storage bucket where table data is stored. This value will be used to construct the storage URI in the following way: `gs://{bucket_name}/{table_folder_root}/{table_folder_subpath}``. If `storage_uri` is provided, this value is ignored. */
  tableFolderSubpath?: string;
}

interface I_ActionConfig_Metadata {
  /** A detailed description of the data object. */
  overview?: string;
  /** Extra properties of the data object. */
  extraProperties?: Record<string, unknown>;
}

interface IDataformTableConfig {
  /** Action type: table. */
  type?: "table";
  /** The name of the table. */
  name?: string;
  /** The dataset (schema) of the table. */
  dataset?: string;
  /** Alias for dataset. The schema/dataset of the action. */
  schema?: string;
  /** The Google Cloud project (database) of the table. */
  project?: string;
  /** Alias for project. The Google Cloud project (database) of the action. */
  database?: string;
  /** Targets of actions that this action is dependent on. */
  dependencyTargets?: I_ActionConfig_Target[];
  /** Shorthand dependency names (alternative to dependencyTargets). */
  dependencies?: string[];
  /** A list of user-defined tags with which the action should be labeled. */
  tags?: string[];
  /** If set to true, this action will not be executed. However, the action can still be depended upon. Useful for temporarily turning off broken actions. */
  disabled?: boolean;
  /** Description of the table. */
  description?: string;
  /** Column descriptions. Map of column name to a string or nested record descriptor. */
  columns?: { [key: string]: I_SqlxColumnDescriptor };
  /** The key by which to partition the table. Typically the name of a timestamp or the date column. See https://cloud.google.com/dataform/docs/partitions-clusters. */
  partitionBy?: string;
  /** The number of days for which BigQuery stores data in each partition. The setting applies to all partitions in a table, but is calculated independently for each partition based on the partition time. */
  partitionExpirationDays?: number;
  /** Declares whether the partitioned table requires a WHERE clause predicate filter that filters the partitioning column. */
  requirePartitionFilter?: boolean;
  /** The keys by which to cluster partitions by. See https://cloud.google.com/dataform/docs/partitions-clusters. */
  clusterBy?: string[];
  /** Key-value pairs for BigQuery labels. */
  labels?: { [key: string]: string };
  /** Key-value pairs of additional options to pass to the BigQuery API. Some options, for example, partitionExpirationDays, have dedicated type/validity checked fields. For such options, use the dedicated fields. */
  additionalOptions?: { [key: string]: string };
  /** When set to true, assertions dependent upon any dependency will be add as dedpendency to this action */
  dependOnDependencyAssertions?: boolean;
  /** Assertions to be run on the dataset. If configured, relevant assertions will automatically be created and run as a dependency of this dataset. */
  assertions?: I_ActionConfig_TableAssertionsConfig;
  /** If true, this indicates that the action only depends on data from explicitly-declared dependencies. Otherwise if false, it indicates that the  action depends on data from a source which has not been declared as a dependency. */
  hermetic?: boolean;
  /** Configuration options for an Iceberg table. */
  iceberg?: I_ActionConfig_IcebergTableConfig;
  /** Metadata for this table. */
  metadata?: I_ActionConfig_Metadata;
  /** Optional. The BigQuery reservation to use for execution. If unset, the value from workflow_settings.yaml is used. If neither is set, default BigQuery behavior applies. Dataform CLI only (GCP Dataform support pending). */
  reservation?: string;
  /** BigQuery-specific options. These can also be set directly at the top level. */
  bigquery?: {
    /** Partition key. Accepts a column name string or a structured object. */
    partitionBy?: string | {
      /** Partition column name. */
      field?: string;
      /** Data type of the partition column. */
      dataType?: "timestamp" | "date" | "datetime" | "int64";
      /** Temporal partitioning granularity. */
      granularity?: "hour" | "day" | "month" | "year";
    };
    /** Clustering columns (max 4). */
    clusterBy?: string[];
    /** Days before partition data expiry. */
    partitionExpirationDays?: number;
    /** Requires a WHERE clause filter on the partition column. */
    requirePartitionFilter?: boolean;
    /** BigQuery resource labels (key-value pairs). */
    labels?: { [key: string]: string };
    /** Extra BigQuery API options passed verbatim. */
    additionalOptions?: { [key: string]: string };
    /** Apache Iceberg options for BigLake Metastore tables. */
    iceberg?: {
      /** Cloud Storage connection resource name. */
      connection?: string;
      /** Storage file format. */
      fileFormat?: "PARQUET";
      /** Cloud Storage bucket name. */
      bucketName?: string;
      /** Root folder inside the bucket. */
      tableFolderRoot?: string;
      /** Sub-folder path for this table. */
      tableFolderSubpath?: string;
    };
  };
}

interface IDataformViewConfig {
  /** Action type: view. */
  type?: "view";
  /** The name of the view. */
  name?: string;
  /** The dataset (schema) of the view. */
  dataset?: string;
  /** Alias for dataset. The schema/dataset of the action. */
  schema?: string;
  /** The Google Cloud project (database) of the view. */
  project?: string;
  /** Alias for project. The Google Cloud project (database) of the action. */
  database?: string;
  /** Targets of actions that this action is dependent on. */
  dependencyTargets?: I_ActionConfig_Target[];
  /** Shorthand dependency names (alternative to dependencyTargets). */
  dependencies?: string[];
  /** A list of user-defined tags with which the action should be labeled. */
  tags?: string[];
  /** If set to true, this action will not be executed. However, the action can still be depended upon. Useful for temporarily turning off broken actions. */
  disabled?: boolean;
  /** Applies the materialized view optimization, see https://cloud.google.com/bigquery/docs/materialized-views-intro. */
  materialized?: boolean;
  /** Optional. Applicable only to materialized view. The key by which to partition the materialized view. Typically the name of a timestamp or the date column. See https://cloud.google.com/bigquery/docs/materialized-views-create#partitioned_materialized_views. */
  partitionBy?: string;
  /** Optional. Applicable only to materialized view. The keys by which to cluster partitions by. See https://cloud.google.com/bigquery/docs/materialized-views-create#cluster_materialized_views. */
  clusterBy?: string[];
  /** Description of the view. */
  description?: string;
  /** Column descriptions. Map of column name to a string or nested record descriptor. */
  columns?: { [key: string]: I_SqlxColumnDescriptor };
  /** Key-value pairs for BigQuery labels. */
  labels?: { [key: string]: string };
  /** Key-value pairs of additional options to pass to the BigQuery API. Some options, for example, partitionExpirationDays, have dedicated type/validity checked fields. For such options, use the dedicated fields. */
  additionalOptions?: { [key: string]: string };
  /** When set to true, assertions dependent upon any dependency will be add as dedpendency to this action */
  dependOnDependencyAssertions?: boolean;
  /** If true, this indicates that the action only depends on data from explicitly-declared dependencies. Otherwise if false, it indicates that the  action depends on data from a source which has not been declared as a dependency. */
  hermetic?: boolean;
  /** Assertions to be run on the dataset. If configured, relevant assertions will automatically be created and run as a dependency of this dataset. */
  assertions?: I_ActionConfig_TableAssertionsConfig;
  /** Metadata for this view. */
  metadata?: I_ActionConfig_Metadata;
  /** Optional. The BigQuery reservation to use for execution. If unset, the value from workflow_settings.yaml is used. If neither is set, default BigQuery behavior applies. Dataform CLI only (GCP Dataform support pending). */
  reservation?: string;
  /** BigQuery-specific options. These can also be set directly at the top level. */
  bigquery?: {
    /** Partition key. Accepts a column name string or a structured object. */
    partitionBy?: string | {
      /** Partition column name. */
      field?: string;
      /** Data type of the partition column. */
      dataType?: "timestamp" | "date" | "datetime" | "int64";
      /** Temporal partitioning granularity. */
      granularity?: "hour" | "day" | "month" | "year";
    };
    /** Clustering columns (max 4). */
    clusterBy?: string[];
    /** Days before partition data expiry. */
    partitionExpirationDays?: number;
    /** Requires a WHERE clause filter on the partition column. */
    requirePartitionFilter?: boolean;
    /** BigQuery resource labels (key-value pairs). */
    labels?: { [key: string]: string };
    /** Extra BigQuery API options passed verbatim. */
    additionalOptions?: { [key: string]: string };
  };
}

/** Does not block any new column(s) from being added, deleted or renamed. */
interface IDataformIncrementalConfig {
  /** Action type: incremental. */
  type?: "incremental";
  /** The name of the incremental table. */
  name?: string;
  /** The dataset (schema) of the incremental table. */
  dataset?: string;
  /** Alias for dataset. The schema/dataset of the action. */
  schema?: string;
  /** The Google Cloud project (database) of the incremental table. */
  project?: string;
  /** Alias for project. The Google Cloud project (database) of the action. */
  database?: string;
  /** Targets of actions that this action is dependent on. */
  dependencyTargets?: I_ActionConfig_Target[];
  /** Shorthand dependency names (alternative to dependencyTargets). */
  dependencies?: string[];
  /** A list of user-defined tags with which the action should be labeled. */
  tags?: string[];
  /** If set to true, this action will not be executed. However, the action can still be depended upon. Useful for temporarily turning off broken actions. */
  disabled?: boolean;
  /** If true, prevents the dataset from being rebuilt from scratch. */
  protected?: boolean;
  /** If set, unique key represents a set of names of columns that will act as a the unique key. To enforce this, when updating the incremental table, Dataform merges rows with `uniqueKey` instead of appending them. */
  uniqueKey?: string[];
  /** Description of the incremental table. */
  description?: string;
  /** Column descriptions. Map of column name to a string or nested record descriptor. */
  columns?: { [key: string]: I_SqlxColumnDescriptor };
  /** The key by which to partition the table. Typically the name of a timestamp or the date column. See https://cloud.google.com/dataform/docs/partitions-clusters. */
  partitionBy?: string;
  /** The number of days for which BigQuery stores data in each partition. The setting applies to all partitions in a table, but is calculated independently for each partition based on the partition time. */
  partitionExpirationDays?: number;
  /** Declares whether the partitioned table requires a WHERE clause predicate filter that filters the partitioning column. */
  requirePartitionFilter?: boolean;
  /** SQL-based filter for when incremental updates are applied. */
  updatePartitionFilter?: string;
  /** The keys by which to cluster partitions by. See https://cloud.google.com/dataform/docs/partitions-clusters. */
  clusterBy?: string[];
  /** Key-value pairs for BigQuery labels. */
  labels?: { [key: string]: string };
  /** Key-value pairs of additional options to pass to the BigQuery API. Some options, for example, partitionExpirationDays, have dedicated type/validity checked fields. For such options, use the dedicated fields. */
  additionalOptions?: { [key: string]: string };
  /** When set to true, assertions dependent upon any dependency will be add as dedpendency to this action */
  dependOnDependencyAssertions?: boolean;
  /** Assertions to be run on the dataset. If configured, relevant assertions will automatically be created and run as a dependency of this dataset. */
  assertions?: I_ActionConfig_TableAssertionsConfig;
  /** If true, this indicates that the action only depends on data from explicitly-declared dependencies. Otherwise if false, it indicates that the  action depends on data from a source which has not been declared as a dependency. */
  hermetic?: boolean;
  /** Defines the action behavior if the selected columns in the query don't the match columns in the target table. */
  onSchemaChange?: "IGNORE" | "FAIL" | "EXTEND" | "SYNCHRONIZE";
  /** Configuration options for an Iceberg table. */
  iceberg?: I_ActionConfig_IcebergTableConfig;
  /** Metadata for this incremental table. */
  metadata?: I_ActionConfig_Metadata;
  /** Optional. The BigQuery reservation to use for execution. If unset, the value from workflow_settings.yaml is used. If neither is set, default BigQuery behavior applies. Dataform CLI only (GCP Dataform support pending). */
  reservation?: string;
  /** BigQuery-specific options. These can also be set directly at the top level. */
  bigquery?: {
    /** Partition key. Accepts a column name string or a structured object. */
    partitionBy?: string | {
      /** Partition column name. */
      field?: string;
      /** Data type of the partition column. */
      dataType?: "timestamp" | "date" | "datetime" | "int64";
      /** Temporal partitioning granularity. */
      granularity?: "hour" | "day" | "month" | "year";
    };
    /** Clustering columns (max 4). */
    clusterBy?: string[];
    /** Days before partition data expiry. */
    partitionExpirationDays?: number;
    /** Requires a WHERE clause filter on the partition column. */
    requirePartitionFilter?: boolean;
    /** SQL filter applied during incremental updates. */
    updatePartitionFilter?: string;
    /** BigQuery resource labels (key-value pairs). */
    labels?: { [key: string]: string };
    /** Extra BigQuery API options passed verbatim. */
    additionalOptions?: { [key: string]: string };
    /** Apache Iceberg options for BigLake Metastore tables. */
    iceberg?: {
      /** Cloud Storage connection resource name. */
      connection?: string;
      /** Storage file format. */
      fileFormat?: "PARQUET";
      /** Cloud Storage bucket name. */
      bucketName?: string;
      /** Root folder inside the bucket. */
      tableFolderRoot?: string;
      /** Sub-folder path for this table. */
      tableFolderSubpath?: string;
    };
  };
}

interface IDataformAssertionConfig {
  /** Action type: assertion. */
  type?: "assertion";
  /** The name of the assertion. */
  name?: string;
  /** The dataset (schema) of the assertion. */
  dataset?: string;
  /** Alias for dataset. The schema/dataset of the action. */
  schema?: string;
  /** The Google Cloud project (database) of the assertion. */
  project?: string;
  /** Alias for project. The Google Cloud project (database) of the action. */
  database?: string;
  /** Targets of actions that this action is dependent on. */
  dependencyTargets?: I_ActionConfig_Target[];
  /** Shorthand dependency names (alternative to dependencyTargets). */
  dependencies?: string[];
  /** A list of user-defined tags with which the action should be labeled. */
  tags?: string[];
  /** If set to true, this action will not be executed. However, the action can still be depended upon. Useful for temporarily turning off broken actions. */
  disabled?: boolean;
  /** Description of the assertion. */
  description?: string;
  /** If true, this indicates that the action only depends on data from explicitly-declared dependencies. Otherwise if false, it indicates that the  action depends on data from a source which has not been declared as a dependency. */
  hermetic?: boolean;
  /** If true, assertions dependent upon any of the dependencies are added as dependencies as well. */
  dependOnDependencyAssertions?: boolean;
  /** Optional. The BigQuery reservation to use for execution. If unset, the value from workflow_settings.yaml is used. If neither is set, default BigQuery behavior applies. Dataform CLI only (GCP Dataform support pending). */
  reservation?: string;
  /** Metadata for this assertion. */
  metadata?: I_ActionConfig_Metadata;
}

interface IDataformOperationsConfig {
  /** Action type: operations. */
  type?: "operations";
  /** The name of the operation. */
  name?: string;
  /** The dataset (schema) of the operation. */
  dataset?: string;
  /** Alias for dataset. The schema/dataset of the action. */
  schema?: string;
  /** The Google Cloud project (database) of the operation. */
  project?: string;
  /** Alias for project. The Google Cloud project (database) of the action. */
  database?: string;
  /** Targets of actions that this action is dependent on. */
  dependencyTargets?: I_ActionConfig_Target[];
  /** Shorthand dependency names (alternative to dependencyTargets). */
  dependencies?: string[];
  /** A list of user-defined tags with which the action should be labeled. */
  tags?: string[];
  /** If set to true, this action will not be executed. However, the action can still be depended upon. Useful for temporarily turning off broken actions. */
  disabled?: boolean;
  /** Declares that this action creates a dataset which should be referenceable as a dependency target, for example by using the `ref` function. */
  hasOutput?: boolean;
  /** Description of the operation. */
  description?: string;
  /** Column descriptions. Map of column name to a string or nested record descriptor. */
  columns?: { [key: string]: I_SqlxColumnDescriptor };
  /** When set to true, assertions dependent upon any dependency will be add as dedpendency to this action */
  dependOnDependencyAssertions?: boolean;
  /** If true, this indicates that the action only depends on data from explicitly-declared dependencies. Otherwise if false, it indicates that the  action depends on data from a source which has not been declared as a dependency. */
  hermetic?: boolean;
  /** Optional. The BigQuery reservation to use for execution. If unset, the value from workflow_settings.yaml is used. If neither is set, default BigQuery behavior applies. Dataform CLI only (GCP Dataform support pending). */
  reservation?: string;
}

interface IDataformDeclarationConfig {
  /** Action type: declaration. */
  type?: "declaration";
  /** The name of the declaration. */
  name?: string;
  /** The dataset (schema) of the declaration. */
  dataset?: string;
  /** Alias for dataset. The schema/dataset of the action. */
  schema?: string;
  /** The Google Cloud project (database) of the declaration. */
  project?: string;
  /** Alias for project. The Google Cloud project (database) of the action. */
  database?: string;
  /** Description of the declaration. */
  description?: string;
  /** Column descriptions. Map of column name to a string or nested record descriptor. */
  columns?: { [key: string]: I_SqlxColumnDescriptor };
  /** A list of user-defined tags with which the action should be labeled. */
  tags?: string[];
}

/** Union of all Dataform config block types */
type DataformConfig = IDataformTableConfig | IDataformViewConfig | IDataformIncrementalConfig | IDataformAssertionConfig | IDataformOperationsConfig | IDataformDeclarationConfig;
