/*
 * Licensed to the Apache Software Foundation (ASF) under one or more
 * contributor license agreements. See the NOTICE file distributed with
 * this work for additional information regarding copyright ownership.
 * The ASF licenses this file to You under the Apache License, Version 2.0
 * (the "License"); you may not use this file except in compliance with
 * the License.  You may obtain a copy of the License at
 *
 *    http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package io.github.rejeb.dataform.language.schema.dts;

import com.fasterxml.jackson.databind.JsonNode;
import com.fasterxml.jackson.databind.node.ArrayNode;
import com.fasterxml.jackson.databind.node.ObjectNode;
import com.intellij.openapi.application.WriteAction;
import com.intellij.openapi.diagnostic.Logger;
import com.intellij.openapi.project.Project;
import com.intellij.openapi.project.ProjectUtil;
import com.intellij.openapi.util.text.StringUtil;
import com.intellij.openapi.vfs.VfsUtil;
import com.intellij.openapi.vfs.VirtualFile;
import io.github.rejeb.dataform.language.schema.json.DataformJsonSchemaGenerator;
import org.jetbrains.annotations.NotNull;

import java.nio.charset.StandardCharsets;
import java.util.*;

public class DataformDtsGeneratorImpl implements DataformDtsGenerator {

    private static final String DTS_PATH = ".dataform/types/dataform.d.ts";

    private final Project project;

    public DataformDtsGeneratorImpl(@NotNull Project project) {
        this.project = project;
    }

    @Override
    public void generateDts() {
        DataformJsonSchemaGenerator schemaGen =
                project.getService(DataformJsonSchemaGenerator.class);

        Optional<ObjectNode> configSchema = schemaGen.generateSqlxConfigSchema();
        if (configSchema.isEmpty()) return;

        ObjectNode root = configSchema.get();

        StringBuilder sb = new StringBuilder();
        sb.append("// Auto-generated by Dataform IntelliJ Plugin — do not edit\n\n");

        ObjectNode defs = (ObjectNode) root.get("$defs");
        Map<String, String> defNames = new LinkedHashMap<>();
        if (defs != null) {
            defs.properties().forEach(entry -> {
                String ifaceName = "I_" + entry.getKey();
                defNames.put(entry.getKey(), ifaceName);
            });
            defs.properties().forEach(entry -> {
                sb.append("interface ").append(defNames.get(entry.getKey())).append(" ");
                appendObjectType(sb, (ObjectNode) entry.getValue(), defNames, "");
                sb.append("\n\n");
            });
        }

        ArrayNode oneOf = (ArrayNode) root.get("oneOf");
        List<String> ifaceNames = new ArrayList<>();
        if (oneOf != null) {
            for (JsonNode branch : oneOf) {
                ObjectNode branchObj = (ObjectNode) branch;
                String sqlxType = branchObj.path("properties").path("type")
                        .path("enum").path(0).asText();
                if (sqlxType.isEmpty()) continue;
                String ifaceName = "IDataform" + StringUtil.capitalize(sqlxType) + "Config";
                ifaceNames.add(ifaceName);

                String desc = branchObj.path("description").asText("");
                if (!desc.isEmpty()) sb.append("/** ").append(desc).append(" */\n");
                sb.append("interface ").append(ifaceName).append(" ");
                appendObjectType(sb, branchObj, defNames, "");
                sb.append("\n\n");
            }
        }

        sb.append("/** Union of all Dataform config block types */\n");
        sb.append("type DataformConfig = ")
                .append(String.join(" | ", ifaceNames))
                .append(";\n");

        writeFile(sb.toString());
    }

    private void appendObjectType(StringBuilder sb, ObjectNode schema,
                                  Map<String, String> defNames, String indent) {
        sb.append("{\n");
        String inner = indent + "  ";
        ObjectNode props = (ObjectNode) schema.get("properties");
        if (props != null) {
            props.properties().forEach(entry -> {
                String propName = entry.getKey();
                ObjectNode propSchema = (ObjectNode) entry.getValue();
                String desc = propSchema.path("description").asText("");
                if (!desc.isEmpty()) {
                    sb.append(inner).append("/** ").append(desc.replace("*/", "* /")).append(" */\n");
                }
                sb.append(inner).append(propName).append("?: ")
                        .append(schemaToTs(propSchema, defNames, inner)).append(";\n");
            });
        }
        sb.append(indent).append("}");
    }

    private String schemaToTs(ObjectNode schema, Map<String, String> defNames, String indent) {
        // $ref
        String ref = schema.path("$ref").asText("");
        if (!ref.isEmpty()) {
            String defKey = ref.replace("#/$defs/", "");
            return defNames.getOrDefault(defKey, "unknown");
        }

        // enum
        JsonNode enumNode = schema.get("enum");
        if (enumNode != null && enumNode.isArray()) {
            List<String> values = new ArrayList<>();
            enumNode.forEach(v -> values.add("\"" + v.asText() + "\""));
            return String.join(" | ", values);
        }

        // oneOf
        JsonNode oneOf = schema.get("oneOf");
        if (oneOf != null && oneOf.isArray()) {
            List<String> variants = new ArrayList<>();
            oneOf.forEach(v -> variants.add(schemaToTs((ObjectNode) v, defNames, indent)));
            return String.join(" | ", variants);
        }

        String type = schema.path("type").asText("");
        return switch (type) {
            case "string" -> "string";
            case "boolean" -> "boolean";
            case "integer",
                 "number" -> "number";
            case "array" -> {
                JsonNode items = schema.get("items");
                String itemType = items != null
                        ? schemaToTs((ObjectNode) items, defNames, indent)
                        : "unknown";
                yield arrayOf(itemType);
            }
            case "object" -> {
                JsonNode addProps = schema.get("additionalProperties");
                if (addProps != null && addProps.isObject()) {
                    String valType = schemaToTs((ObjectNode) addProps, defNames, indent);
                    yield "{ [key: string]: " + valType + " }";
                }
                if (schema.has("properties")) {
                    StringBuilder nested = new StringBuilder();
                    appendObjectType(nested, schema, defNames, indent);
                    yield nested.toString();
                }
                yield "Record<string, unknown>";
            }
            default -> "unknown";
        };
    }

    private void writeFile(String content) {
        byte[] bytes = content.getBytes(StandardCharsets.UTF_8);
        try {
            VirtualFile root = ProjectUtil.guessProjectDir(project);
            if (root == null) return;
            VirtualFile existing = root.findFileByRelativePath(DTS_PATH);
            if (existing != null && Arrays.equals(existing.contentsToByteArray(), bytes)) return;

            WriteAction.runAndWait(() -> {
                VfsUtil.createDirectoryIfMissing(root, ".dataform/types").findOrCreateChildData(this, "dataform.d.ts").setBinaryContent(bytes);
            });
        } catch (Exception e) {
            Logger.getInstance(getClass()).error("Failed to write dataform.d.ts", e);
        }
    }

    static String arrayOf(String itemType) {
        return itemType.contains(" | ") ? "(" + itemType + ")[]" : itemType + "[]";
    }
}
