/*
 * Licensed to the Apache Software Foundation (ASF) under one or more
 * contributor license agreements. See the NOTICE file distributed with
 * this work for additional information regarding copyright ownership.
 * The ASF licenses this file to You under the Apache License, Version 2.0
 * (the "License"); you may not use this file except in compliance with
 * the License.  You may obtain a copy of the License at
 *
 *    http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package io.github.rejeb.dataform.language.schema.dts;

import com.fasterxml.jackson.databind.JsonNode;
import com.fasterxml.jackson.databind.node.ArrayNode;
import com.fasterxml.jackson.databind.node.ObjectNode;
import com.intellij.openapi.project.Project;
import com.intellij.openapi.vfs.VirtualFile;
import io.github.rejeb.dataform.language.schema.json.DataformJsonSchemaGenerator;
import io.github.rejeb.dataform.language.schema.json.ProtoModel;
import org.jetbrains.annotations.NotNull;

import java.util.*;

public class DataformDtsGeneratorImpl implements DataformDtsGenerator {

    private final Project project;

    public DataformDtsGeneratorImpl(@NotNull Project project) {
        this.project = project;
    }

    @Override
    public void generateDts() {
        DataformJsonSchemaGenerator schemaGen =
                project.getService(DataformJsonSchemaGenerator.class);

        Optional<ObjectNode> configSchema = schemaGen.generateSqlxConfigSchema();
        if (configSchema.isEmpty()) return;

        ObjectNode root = configSchema.get();

        StringBuilder sb = new StringBuilder();
        sb.append("// Auto-generated by Dataform IntelliJ Plugin — do not edit\n\n");

        ObjectNode defs = (ObjectNode) root.get("$defs");
        Map<String, String> defNames = new LinkedHashMap<>();
        if (defs != null) {
            defs.properties().forEach(entry -> {
                String ifaceName = "I_" + entry.getKey();
                defNames.put(entry.getKey(), ifaceName);
            });
            defs.properties().forEach(entry -> {
                sb.append("interface ").append(defNames.get(entry.getKey())).append(" ");
                appendObjectType(sb, (ObjectNode) entry.getValue(), defNames, "");
                sb.append("\n\n");
            });
        }

        ArrayNode oneOf = (ArrayNode) root.get("oneOf");
        List<String> ifaceNames = new ArrayList<>();
        if (oneOf != null) {
            for (JsonNode branch : oneOf) {
                ObjectNode branchObj = (ObjectNode) branch;
                String sqlxType = branchObj.path("properties").path("type")
                        .path("enum").path(0).asText();
                if (sqlxType.isEmpty()) continue;
                String ifaceName = "IDataform" + capitalize(sqlxType) + "Config";
                ifaceNames.add(ifaceName);

                String desc = branchObj.path("description").asText("");
                if (!desc.isEmpty()) sb.append("/** ").append(desc).append(" */\n");
                sb.append("interface ").append(ifaceName).append(" ");
                appendObjectType(sb, branchObj, defNames, "");
                sb.append("\n\n");
            }
        }

        sb.append("/** Union of all Dataform config block types */\n");
        sb.append("type DataformConfig = ")
                .append(String.join(" | ", ifaceNames))
                .append(";\n");

        writeFile(sb.toString());
    }

    private void appendObjectType(StringBuilder sb, ObjectNode schema,
                                  Map<String, String> defNames, String indent) {
        sb.append("{\n");
        String inner = indent + "  ";
        ObjectNode props = (ObjectNode) schema.get("properties");
        if (props != null) {
            props.properties().forEach(entry -> {
                String propName = entry.getKey();
                ObjectNode propSchema = (ObjectNode) entry.getValue();
                String desc = propSchema.path("description").asText("");
                if (!desc.isEmpty()) {
                    sb.append(inner).append("/** ").append(desc.replace("*/", "* /")).append(" */\n");
                }
                sb.append(inner).append(propName).append("?: ")
                        .append(schemaToTs(propSchema, defNames, inner)).append(";\n");
            });
        }
        sb.append(indent).append("}");
    }

    private String schemaToTs(ObjectNode schema, Map<String, String> defNames, String indent) {
        // $ref
        String ref = schema.path("$ref").asText("");
        if (!ref.isEmpty()) {
            String defKey = ref.replace("#/$defs/", "");
            return defNames.getOrDefault(defKey, "unknown");
        }

        // enum
        JsonNode enumNode = schema.get("enum");
        if (enumNode != null && enumNode.isArray()) {
            List<String> values = new ArrayList<>();
            enumNode.forEach(v -> values.add("\"" + v.asText() + "\""));
            return String.join(" | ", values);
        }

        // oneOf
        JsonNode oneOf = schema.get("oneOf");
        if (oneOf != null && oneOf.isArray()) {
            List<String> variants = new ArrayList<>();
            oneOf.forEach(v -> variants.add(schemaToTs((ObjectNode) v, defNames, indent)));
            return String.join(" | ", variants);
        }

        String type = schema.path("type").asText("");
        return switch (type) {
            case "string" -> "string";
            case "boolean" -> "boolean";
            case "integer",
                 "number" -> "number";
            case "array" -> {
                JsonNode items = schema.get("items");
                String itemType = items != null
                        ? schemaToTs((ObjectNode) items, defNames, indent)
                        : "unknown";
                yield itemType + "[]";
            }
            case "object" -> {
                JsonNode addProps = schema.get("additionalProperties");
                if (addProps != null && addProps.isObject()) {
                    String valType = schemaToTs((ObjectNode) addProps, defNames, indent);
                    yield "{ [key: string]: " + valType + " }";
                }
                if (schema.has("properties")) {
                    StringBuilder nested = new StringBuilder();
                    appendObjectType(nested, schema, defNames, indent);
                    yield nested.toString();
                }
                yield "Record<string, unknown>";
            }
            default -> "unknown";
        };
    }

    private String fieldToTs(ProtoModel.ProtoField field,
                             Map<String, ProtoModel.ProtoMessage> messageIndex,
                             Map<String, ProtoModel.ProtoEnum> enumIndex,
                             Set<String> visiting) {
        if (field.isMap) {
            return "{ [key: string]: " + scalarToTs(field.mapValueType, messageIndex, enumIndex, visiting) + " }";
        }
        String base = scalarToTs(field.type, messageIndex, enumIndex, visiting);
        return field.repeated ? base + "[]" : base;
    }

    private String scalarToTs(String type,
                              Map<String, ProtoModel.ProtoMessage> messageIndex,
                              Map<String, ProtoModel.ProtoEnum> enumIndex,
                              Set<String> visiting) {
        return switch (type) {
            case "string", "bytes" -> "string";
            case "bool" -> "boolean";
            case "int32", "int64", "uint32", "uint64",
                 "sint32", "sint64", "fixed32", "fixed64",
                 "sfixed32", "sfixed64", "float", "double" -> "number";
            case "google.protobuf.Struct" -> "Record<string, unknown>";
            default -> {
                ProtoModel.ProtoEnum protoEnum = enumIndex.get(type);
                if (protoEnum != null) {
                    yield protoEnum.values.stream()
                            .map(v -> "\"" + v + "\"")
                            .reduce((a, b) -> a + " | " + b)
                            .orElse("string");
                }
                ProtoModel.ProtoMessage nested = messageIndex.get(type);
                if (nested != null && visiting.add(type)) {
                    StringBuilder sb = new StringBuilder("{\n");
                    for (ProtoModel.ProtoField f : nested.fields) {
                        sb.append("    ").append(f.camelName).append("?: ")
                                .append(fieldToTs(f, messageIndex, enumIndex, visiting)).append(";\n");
                    }
                    visiting.remove(type);
                    sb.append("  }");
                    yield sb.toString();
                }
                yield "unknown";
            }
        };
    }

    private void writeFile(String content) {
        try {
            com.intellij.openapi.vfs.VirtualFile root =
                    com.intellij.openapi.project.ProjectUtil.guessProjectDir(project);
            if (root == null) return;

            VirtualFile dataformDir = root.findChild(".dataform");
            if (dataformDir == null) dataformDir = root.createChildDirectory(this, ".dataform");

            VirtualFile typesDir = dataformDir.findChild("types");
            if (typesDir == null) typesDir = dataformDir.createChildDirectory(this, "types");
            com.intellij.openapi.vfs.VirtualFile dtsFile =
                    typesDir.findOrCreateChildData(this, "dataform.d.ts");

            com.intellij.openapi.application.WriteAction.runAndWait(() ->
                    dtsFile.setBinaryContent(content.getBytes(java.nio.charset.StandardCharsets.UTF_8))
            );
        } catch (Exception e) {
            com.intellij.openapi.diagnostic.Logger
                    .getInstance(getClass()).error("Failed to write dataform.d.ts", e);
        }
    }

    private String capitalize(String s) {
        return s.isEmpty() ? s : Character.toUpperCase(s.charAt(0)) + s.substring(1);
    }

}
